# SPDX-License-Identifier: MPL-2.0
# Utilities for reusing the legacy Makefile configuration snippets inside
# the CMake build.  The parser is intentionally limited to the variables
# that influence compiler/linker flags and feature toggles.

function(trdp_load_legacy_config path prefix)
    if(NOT IS_ABSOLUTE "${path}")
        message(FATAL_ERROR "trdp_load_legacy_config() requires an absolute path")
    endif()
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Unable to read legacy config: ${path}")
    endif()

    file(STRINGS "${path}" _trdp_config_lines)

    set(_trdp_arch "")
    set(_trdp_target_os "")
    set(_trdp_target_vos "")
    set(_trdp_cflags)
    set(_trdp_ldflags)
    set(_trdp_incpath)

    set(_trdp_bool_vars TSN_SUPPORT SOA_SUPPORT HIGH_PERF_INDEXED HIGH_PERF_BASE2)
    foreach(_var IN LISTS _trdp_bool_vars)
        set(_trdp_${_var} FALSE)
    endforeach()

    foreach(_line IN LISTS _trdp_config_lines)
        string(REGEX REPLACE "#.*$" "" _trimmed "${_line}")
        string(STRIP "${_trimmed}" _trimmed)
        if(_trimmed STREQUAL "")
            continue()
        endif()
        if(NOT _trimmed MATCHES "^([A-Za-z0-9_]+)[ \t]*([+]?=)[ \t]*(.*)$")
            continue()
        endif()
        set(_var "${CMAKE_MATCH_1}")
        set(_op "${CMAKE_MATCH_2}")
        set(_value "${CMAKE_MATCH_3}")
        string(STRIP "${_value}" _value)

        if(_var STREQUAL "ARCH")
            set(_trdp_arch "${_value}")
        elseif(_var STREQUAL "TARGET_OS")
            set(_trdp_target_os "${_value}")
        elseif(_var STREQUAL "TARGET_VOS")
            set(_trdp_target_vos "${_value}")
        elseif(_var STREQUAL "CFLAGS")
            separate_arguments(_tokens UNIX_COMMAND "${_value}")
            if(_op STREQUAL "=")
                set(_trdp_cflags)
            endif()
            list(APPEND _trdp_cflags ${_tokens})
        elseif(_var STREQUAL "LDFLAGS")
            separate_arguments(_tokens UNIX_COMMAND "${_value}")
            if(_op STREQUAL "=")
                set(_trdp_ldflags)
            endif()
            list(APPEND _trdp_ldflags ${_tokens})
        elseif(_var STREQUAL "INCPATH")
            separate_arguments(_tokens UNIX_COMMAND "${_value}")
            if(_op STREQUAL "=")
                set(_trdp_incpath)
            endif()
            list(APPEND _trdp_incpath ${_tokens})
        elseif(_var IN_LIST _trdp_bool_vars)
            string(TOUPPER "${_value}" _value_upper)
            if(_value_upper MATCHES "^(1|ON|TRUE|Y|YES)$")
                set(_trdp_${_var} TRUE)
            else()
                set(_trdp_${_var} FALSE)
            endif()
        endif()
    endforeach()

    set(_trdp_inc_dirs)
    foreach(_entry IN LISTS _trdp_incpath)
        if(_entry MATCHES "^-I(.+)$")
            list(APPEND _trdp_inc_dirs "${CMAKE_MATCH_1}")
        elseif(NOT _entry STREQUAL "")
            list(APPEND _trdp_inc_dirs "${_entry}")
        endif()
    endforeach()

    set(_trdp_link_libs)
    set(_trdp_link_options)
    foreach(_entry IN LISTS _trdp_ldflags)
        if(_entry MATCHES "^-l(.+)$")
            list(APPEND _trdp_link_libs "${CMAKE_MATCH_1}")
        elseif(NOT _entry STREQUAL "")
            list(APPEND _trdp_link_options "${_entry}")
        endif()
    endforeach()

    set(${prefix}_ARCH "${_trdp_arch}" PARENT_SCOPE)
    set(${prefix}_TARGET_OS "${_trdp_target_os}" PARENT_SCOPE)
    set(${prefix}_TARGET_VOS "${_trdp_target_vos}" PARENT_SCOPE)
    set(${prefix}_CFLAGS ${_trdp_cflags} PARENT_SCOPE)
    set(${prefix}_INCLUDE_DIRS ${_trdp_inc_dirs} PARENT_SCOPE)
    set(${prefix}_LINK_LIBS ${_trdp_link_libs} PARENT_SCOPE)
    set(${prefix}_LINK_OPTIONS ${_trdp_link_options} PARENT_SCOPE)
    foreach(_var IN LISTS _trdp_bool_vars)
        set(${prefix}_${_var} "${_trdp_${_var}}" PARENT_SCOPE)
    endforeach()
endfunction()
